
server:
  port: 8080

spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:mysql://139.196.184.230:3306/oauth?useSSL=false
    username: root
    password: Cs@20180616
    driver-class-name: com.mysql.jdbc.Driver